# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(size=(7,7))
tensor_A, tensor_A.shape

(tensor([[0.7275, 0.0587, 0.2113, 0.9896, 0.5114, 0.2623, 0.4814],
         [0.6056, 0.4081, 0.4955, 0.0842, 0.4686, 0.5442, 0.7075],
         [0.2326, 0.4302, 0.3794, 0.7136, 0.0996, 0.3816, 0.0603],
         [0.7650, 0.5866, 0.2616, 0.0509, 0.4257, 0.0834, 0.1547],
         [0.7448, 0.6711, 0.8718, 0.2652, 0.3160, 0.2804, 0.1630],
         [0.6098, 0.4705, 0.0098, 0.8932, 0.7670, 0.8267, 0.4689],
         [0.0222, 0.6619, 0.4449, 0.2335, 0.2104, 0.0652, 0.5667]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor_B = torch.rand(size=(1,7))

# Perform matrix multiplication 
mat_mul = tensor.matmul(tensor_A*tensor_B.T)
mat_mul, mat_mul.shape

(tensor([[1.1389, 0.7320, 0.7412, 0.8888, 0.8314, 0.7007, 0.8402],
         [1.0270, 0.8177, 0.7491, 0.8668, 0.7716, 0.5900, 0.8332],
         [1.1177, 0.7785, 0.8063, 1.0370, 0.7891, 0.5625, 0.7539],
         [1.0741, 0.9489, 0.6153, 0.6856, 0.7639, 0.4871, 0.6305],
         [0.7813, 0.5723, 0.3913, 0.6207, 0.5638, 0.3269, 0.4770],
         [0.9091, 0.6361, 0.7254, 0.8395, 0.6083, 0.4087, 0.6225],
         [0.8812, 0.7914, 0.5995, 0.4765, 0.5581, 0.3588, 0.3830]]),
 torch.Size([7, 7]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
import random
torch.manual_seed(0)

# Create two random tensors
random_tensor_A = torch.rand(size=(7,7))
random_tensor_B = torch.rand(size=(1,7))

# Matrix multiply tensors
matrix_multiply_tensor = torch.mm(random_tensor_A , random_tensor_B.T)
matrix_multiply_tensor, matrix_multiply_tensor.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed = 1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_X = torch.rand(size=(2,3)).to(device)
tensor_Y = torch.rand(size=(2,3)).to(device)
tensor_X, tensor_Y

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
matrix_mul = torch.matmul(tensor_X, tensor_Y.T)
matrix_mul, matrix_mul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
matrix_mul_max = torch.max(matrix_mul)

# Find min
matrix_mul_min = torch.min(matrix_mul)

matrix_mul_max, matrix_mul_min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
max_index = torch.argmax(matrix_mul)

# Find arg min
min_index = torch.argmin(matrix_mul)

max_index, min_index

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_P = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_Q = tensor_P.squeeze()

# Print out tensors and their shapes
print(f"{tensor_P, tensor_P.shape}, \n {tensor_Q, tensor_Q.shape}")



(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10])), 
 (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
